name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Compile
      run: make
    - name: Clean
      run: make fclean
