name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Compile
      run: make
    - name: Generate tests
      run: ( cd test ; bash ./generate.sh )
    - name: Compile tests
      run: ( cd test ; make )
    - name: Run tests
      run: ( cd test ; make test )
    - name: Clean
      run: make fclean
